{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $site_url=ezini("SiteSettings","SiteURL")}
{set-block scope=root variable=subject}{"%siteurl forgot password"|i18n("mbpaex/userpaex/forgotpassword",,hash('%siteurl',$site_url))}{/set-block}
{"Your account information"|i18n('design/standard/user/forgotpassword')}
{"Email"|i18n('design/standard/user/forgotpassword')}: {$user.email}

{"Click here to set your new password"|i18n('mbpaex/userpaex/forgotpassword')}:
{concat("userpaex/forgotpassword/", $hash_key, '/')|ezurl(no)}

{"This link is valid until %1, after that time you should generate a new one."|i18n('mbpaex/userpaex/forgotpassword',,hash('%1',$hash_key_lifetime))}
{undef $site_url}
