{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="border-box"><div class="tl"><div class="tr"><div class="br"><div class="bl"><div class="box-content float-break">
	<div class="border-ml"><div class="border-mr"><div class="border-mc">

{if $link}
    <p>
    {"A mail has been sent to the following email address: %1. This email contains a link you need to click so that we can confirm that the correct user is getting the new password."|i18n('mbpaex/userpaex/forgotpassword',,array($email))}
    </p>
{else}
    {if $wrong_email}
        <div class="warning">
            <h2>{"There is no registered user with that email address."|i18n('mbpaex/userpaex/forgotpassword')}</h2>
        </div>
    {/if}
    {if $password_form}
        {if $password_changed}
            <p>
            {"The password has been changed successfully."|i18n('mbpaex/userpaex/forgotpassword')}
            </p>
        {else}
            {if $newPasswordNotMatch}
                <div class="warning">
                    <h2>{"The passwords do not match. Please, be sure to enter the same password in both fields."|i18n('mbpaex/userpaex/forgotpassword')}</h2>
                </div>
            {/if}
            {if $newPasswordNotValidate}
                <div class="warning">
                    <h2>{"The new password is invalid, please choose new one."|i18n('mbpaex/userpaex/forgotpassword')}</h2>
                </div>
            {/if}
            {if $newPasswordMustDiffer}
                <div class="warning">
                    <h2>{"New password must be different from the old one. Please choose another password."|i18n('mbpaex/userpaex')}</h2>
                </div>
            {/if}                    
           
            <form method="post" name="forgotpassword" action={concat("/userpaex/forgotpassword/",$HashKey)|ezurl}>
                <div class="maincontentheader">
                    <h1>{"Choose a new password"|i18n('mbpaex/userpaex/forgotpassword')}</h1>
                </div>
                
                <p>
                    {"Enter your desired new password in the form below."|i18n('mbpaex/userpaex/forgotpassword')}
                </p>
                
                <div class="block">
                    <label for="password">{"Password"|i18n('mbpaex/userpaex/forgotpassword')}:</label>
                    <div class="labelbreak"></div>
                    <input class="halfbox" type="password" name="NewPassword" size="20" value="" />
                    <label for="password">{"Password Confirm"|i18n('mbpaex/userpaex/forgotpassword')}:</label>
                    <div class="labelbreak"></div>
                    <input class="halfbox" type="password" name="NewPasswordConfirm" size="20" value="" />
                </div>
                
                <div class="buttonblock">
                    <input class="button" type="submit" name="ChangePasswdButton" value="{'Change password'|i18n('mbpaex/userpaex/forgotpassword')}" />
                    <input type="hidden" name="HashKey" value="{$HashKey}" />
                </div>
            </form>
        {/if}
    {else}
        {if $wrong_key}
            <div class="warning">
                <h2>{"The key is invalid or has been used. "|i18n('mbpaex/userpaex/forgotpassword')}</h2>
            </div>
        {else}
            <form method="post" name="forgotpassword" action={"/userpaex/forgotpassword/"|ezurl}>
                <div class="maincontentheader">
                    <h1>{"Have you forgotten your password?"|i18n('mbpaex/userpaex/forgotpassword')}</h1>
                </div>
                
                <p>
                    {"If you have forgotten your password we can generate a new one for you. All you need to do is to enter your email address and we will create a new password for you."|i18n('mbpaex/userpaex/forgotpassword')}
                </p>
                
                <div class="block">
                    <label for="email">{"Email"|i18n('mbpaex/userpaex/forgotpassword')}:</label>
                    <div class="labelbreak"></div>
                    <input class="halfbox" type="text" name="UserEmail" size="40" value="{$wrong_email|wash}" />
                </div>
                
                <div class="buttonblock">
                    <input class="button" type="submit" name="GenerateButton" value="{'Generate new password'|i18n('mbpaex/userpaex/forgotpassword')}" />
                </div>
            </form>
        {/if}
    {/if}
{/if}

</div></div></div>
</div></div></div></div></div></div>
